name: help4kids
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  dart_frog: ^1.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  dart_jsonwebtoken: ^2.2.1
  bcrypt: ^1.1.3
  uuid: ^3.0.4
#  use this git https://github.com/Marc-R2/mysql1_dart
  mysql1: ^0.20.0


dev_dependencies:
  freezed: ^2.1.0
  build_runner: ^2.2.0
  json_serializable: ^6.2.0
  test: ^1.16.0
